FROM debian:strech

RUN apt-get update -y     && apt-get install -y     bc     bison     build-essential     curl     flex     clang     libncurses5-dev     python-dev     wget     && rm -rf /var/lib/apt/lists/*
